networks:
  apps:
    external: true

volumes:
  am-i-in-a-meeting-api-data:

services:
  am-i-in-a-meeting-api:
    container_name: am-i-in-a-meeting-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - apps
    restart: unless-stopped
    volumes:
      - am-i-in-a-meeting-api-data:/data